### ISSUE TITLE
FE17 - Task Tracker

### ISSUE THREAD

**Issue by Pine1611** [Pine1611/frontend-projects#48]
Create a task tracker with a to-do list using JavaScript.
Tasks: 

- [x] Create a task tracker that lets users add new tasks.
- [x] Mark them as complete, or delete them.
- [x] Completed tasks will be moved to the end of the list and will have strikethrough.
- [x] Users can unmark tasks to return them to the pending list.
